name: update-blacklist

on:
  schedule:
    - cron: '0 14 * * 6'
  workflow_dispatch:

jobs:
  update-blacklist:
    runs-on: macos-latest
    environment: update-blacklist
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          python-version: 3.13

      - name: Run Python script
        env:
          COOKIES_BASE64: ${{ secrets.COOKIES_BASE64 }}
          BAHA_ACCOUNT: ${{ secrets.BAHA_ACCOUNT }}
          BAHA_PASSWORD: ${{ secrets.BAHA_PASSWORD }}
        run: uv run -m baha_blacklist.actions

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%S+08:00")
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add blacklist.txt
            git commit -m "[ci skip] chore: automated update at $CURRENT_TIME" --no-verify
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
